"""
Build the clean canonical release ZIP.

Reproducible on purpose: the exclusion rules live here as code rather
than in a one-off shell command, so the next release is built the same
way and the reasoning for each exclusion is recorded next to it.

Refuses to produce a ZIP if anything matching a secret pattern would be
included - a release that leaks .env is worse than no release.

    python hafnot_build_release_zip.py
"""

from __future__ import annotations

import json
import re
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "HAFNOT_FINAL_CANONICAL.zip"

# Directories never shipped, with the reason.
EXCLUDED_DIRS = {
    ".venv": "virtual environment",
    ".ctrader_venv": "virtual environment",
    "__pycache__": "bytecode cache",
    ".pytest_cache": "test cache",
    ".git": "version control internals",
    "archive_superseded": "already-archived superseded code; duplicate pipelines",
    "node_modules": "not applicable, excluded by policy",
}

# Path prefixes (relative, forward slashes) never shipped.
EXCLUDED_PREFIXES = {
    "data/openapi": "~2 GB of raw market event logs; regenerated live by the market worker",
    "data/live": "live bar cache; regenerated by hafnot_live_bar_feed.py within minutes",
    "data/runtime": "runtime logs",
    "data/historical/bars_backup_before_dedup_20260912": "local backup of the pre-dedupe research corpus (~47 MB)",
    "data/ctrader_oauth_tokens.json": "OAuth tokens - credential material",
    "data/ctrader_authorized_account.json": "account identifiers tied to a live login",
}

# Individual files never shipped.
EXCLUDED_FILES = {
    ".env": "contains real credentials",
    "HAFNOT_FINAL_CANONICAL.zip": "the output of this script",
}

# Suffix patterns for duplicate backup copies (verified unreferenced by
# any import before being excluded).
EXCLUDED_NAME_PARTS = (
    "multi_symbol_paper_PRE_",
    "multi_symbol_paper_BEFORE_",
)

# Anything matching these must never appear in the archive. If one does,
# the build aborts rather than shipping it.
SECRET_GUARD_NAMES = (".env",)
SECRET_GUARD_SUBSTRINGS = ("oauth_tokens", "authorized_account")


def should_exclude(relative: Path) -> str | None:
    parts = relative.parts
    posix = relative.as_posix()

    for part in parts:
        if part in EXCLUDED_DIRS:
            return f"{part} ({EXCLUDED_DIRS[part]})"

    if relative.name in EXCLUDED_FILES:
        return f"{relative.name} ({EXCLUDED_FILES[relative.name]})"

    for prefix, reason in EXCLUDED_PREFIXES.items():
        if posix == prefix or posix.startswith(prefix + "/"):
            return f"{prefix} ({reason})"

    for fragment in EXCLUDED_NAME_PARTS:
        if fragment in relative.name:
            return f"{relative.name} (duplicate backup copy)"

    if relative.suffix in {".pyc", ".pyo"}:
        return "compiled bytecode"

    return None


def violates_secret_guard(relative: Path) -> bool:
    if relative.name in SECRET_GUARD_NAMES:
        return True
    lowered = relative.as_posix().lower()
    return any(token in lowered for token in SECRET_GUARD_SUBSTRINGS)


# File NAMES are not enough: on 2026-09-14 .env.example was found to hold the real
# cTrader client ID and secret, and only .env was excluded. Every included text file's
# CONTENT is now checked against the real credential values.
SENSITIVE_KEY = re.compile(r"(secret|token|password|client_id|api_key)", re.I)
TEXT_SUFFIXES = {".py", ".json", ".jsonl", ".txt", ".md", ".ps1", ".bat", ".cmd", ".toml", ".ini", ".cfg",
                 ".yaml", ".yml", ".example", ".env", ".csv", ".html", ""}
MAX_SCAN_BYTES = 20 * 1024 * 1024


def known_secret_values(root: Path) -> list[str]:
    """Credential values from .env and the OAuth token file (never printed)."""

    values: list[str] = []
    env = root / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8", errors="ignore").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, value = line.split("=", 1)
                value = value.strip().strip('"').strip("'")
                if SENSITIVE_KEY.search(key) and len(value) >= 8:
                    values.append(value)
    tokens = root / "data" / "ctrader_oauth_tokens.json"
    if tokens.exists():
        try:
            data = json.loads(tokens.read_text(encoding="utf-8"))
            values += [str(v) for k, v in data.items() if SENSITIVE_KEY.search(str(k)) and len(str(v)) >= 8]
        except Exception:
            pass
    return values


def files_containing_secrets(root: Path, relatives: list[Path], secrets: list[str]) -> list[Path]:
    if not secrets:
        return []
    leaks = []
    for relative in relatives:
        path = root / relative
        if path.suffix.lower() not in TEXT_SUFFIXES or path.stat().st_size > MAX_SCAN_BYTES:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(secret in text for secret in secrets):
            leaks.append(relative)
    return leaks


def main() -> None:
    included: list[Path] = []
    excluded_reasons: dict[str, int] = {}

    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue

        relative = path.relative_to(ROOT)
        reason = should_exclude(relative)

        if reason:
            key = reason.split(" (")[0]
            excluded_reasons[key] = excluded_reasons.get(key, 0) + 1
            continue

        included.append(relative)

    leaks = [p for p in included if violates_secret_guard(p)]
    leaks += [p for p in files_containing_secrets(ROOT, included, known_secret_values(ROOT)) if p not in leaks]
    if leaks:
        print("[ABORT] Refusing to build - these would leak credential material (by name, or containing a")
        print("        credential value from .env or the OAuth token file):")
        for leak in leaks:
            print(f"  {leak.as_posix()}")
        sys.exit(1)

    if OUTPUT.exists():
        OUTPUT.unlink()

    total_bytes = 0
    with zipfile.ZipFile(OUTPUT, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for relative in sorted(included):
            source = ROOT / relative
            total_bytes += source.stat().st_size
            archive.write(source, relative.as_posix())

    print("=" * 70)
    print(" HAFNOT RELEASE ZIP")
    print("=" * 70)
    print(f"Output        : {OUTPUT.name}")
    print(f"Files included: {len(included)}")
    print(f"Uncompressed  : {total_bytes / (1024 ** 2):.1f} MB")
    print(f"Compressed    : {OUTPUT.stat().st_size / (1024 ** 2):.1f} MB")
    print(f"Built at      : {datetime.now(timezone.utc).isoformat()}")
    print()
    print("Excluded (count by rule):")
    for key, count in sorted(excluded_reasons.items(), key=lambda kv: -kv[1]):
        print(f"  {count:>6}  {key}")
    print("=" * 70)


if __name__ == "__main__":
    main()
